# Vectorisation

I decided to split the files being that some steps that where covered to understand the under workings were more pythonically done in here, i.e. the use of lambda to apply tokenisation was done by a function the sklearn library
Taking the tokenised stemmed or lemmatised text row by row or say line by line and counting eah word occurence as they appear all through the document, counting each word per cell.
This words form columns and are uniquely occuring through the dataset

In [1]:
import pandas as pd
import nltk
import string
import re
import csv

In [2]:
# read dataset in
df = pd.read_csv('SMSSpamCollection.tsv', sep='\t', header=None)

# set headers
df.columns = ['label', 'body_text']
df.head()

  label                                          body_text
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham                I HAVE A DATE ON SUNDAY WITH WILL!!

### Load punctuations, stopwords and parser the stemming function into an object

In [3]:
pd.set_option('display.max_colwidth', 100)
punct = string.punctuation
stop_words = nltk.corpus.stopwords.words('english')
ps = nltk.PorterStemmer()
# wn = nltk.WordNetLemmatizer()
print(punct, "\n", stop_words)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
 ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

### Create function to remove punctuations, tokenise text, remove stopwords and preform stemming

In [4]:
def cleaning(text):
    text = "".join([word.lower() for word in text if word not in punct])
    tokens = re.split('\W+', text)
    text = [ps.stem(word) for word in tokens if word not in stop_words]
    return text

### Apply count vectorise and fit and transform it on the body text

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# store the vectoriser in an object ( this is called instantiation of object)
count_vect = CountVectorizer(analyzer=cleaning)

# fit transform data to document term matrix
X_counts = count_vect.fit_transform(df['body_text'])

print(type(X_counts))
print(X_counts.shape)
print(count_vect.get_feature_names_out())

<class 'scipy.sparse._csr.csr_matrix'>
(5568, 8107)
['' '0' '008704050406' ... 'ü' 'üll' '〨ud']

In [6]:
# get smaller data
df_sample = df[0:20] 
df_sample.head()

,label,body_text
0,ham,I've been searching for the right words to thank you for this breather. I promise i wont take yo...
1,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...
2,ham,"Nah I don't think he goes to usf, he lives around here though"
3,ham,Even my brother is not like to speak with me. They treat me like aids patent.
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!

In [7]:
# instantiate vectoriser into an object
count_vect_sample = CountVectorizer(analyzer=cleaning)

# fit and transform by applying vectoriser to the stemmed text to make document term matrix
X_counts_sample = count_vect_sample.fit_transform(df_sample['body_text'])

print(X_counts_sample.shape)
print(count_vect_sample.get_feature_names_out())

(20, 201)
['08002986030' '08452810075over18' '09061701461' '1' '100' '100000' '11'
 '12' '150pday' '16' '2' '20000' '2005' '21st' '3' '4' '4403ldnw1a7rw18'
 '4txtú120' '6day' '81010' '87077' '87121' '87575' '9' '900' 'aft' 'aid'
 'alreadi' 'anymor' 'appli' 'ard' 'around' 'b' 'bless' 'breather'
 'brother' 'call' 'caller' 'callertun' 'camera' 'cash' 'chanc' 'claim'
 'click' 'co' 'code' 'colour' 'comin' 'comp' 'copi' 'cost' 'credit' 'cri'
 'csh11' 'cup' 'custom' 'da' 'date' 'dont' 'eg' 'eh' 'england' 'enough'
 'entitl' 'entri' 'even' 'fa' 'feel' 'final' 'fine' 'finish' 'first'
 'free' 'friend' 'fulfil' 'go' 'goalsteam' 'goe' 'gonna' 'gota' 'grant'
 'ha' 'help' 'hl' 'home' 'hour' 'httpwap' 'im' 'info' 'ive' 'jackpot'
 'joke' 'k' 'kim' 'kl341' 'lar' 'latest' 'lccltd' 'like' 'link' 'live'
 'lor' 'lunch' 'macedonia' 'make' 'may' 'mell' 'membership' 'messag'
 'minnaminungint' 'miss' 'mobil' 'month' 'nah' 'name' 'nation' 'naughti'
 'network' 'news' 'next' 'nurungu' 'oh' 'oru' 'patent' 'pay' 'per' 'pobox'
 'poboxox36504w45wq' 'pound' 'press' 'prize' 'promis' 'questionstd' 'r'
 'ratetc' 'receiv' 'receivea' 'rememb' 'repli' 'request' 'reward' 'right'
 'scotland' 'search' 'select' 'send' 'serious' 'set' 'six' 'smth' 'soon'
 'speak' 'spell' 'stock' 'str' 'stuff' 'sunday' 'take' 'talk' 'tc' 'team'
 'text' 'thank' 'think' 'though' 'time' 'tkt' 'today' 'tonight' 'treat'
 'tri' 'trywal' 'tsandc' 'txt' 'u' 'updat' 'ur' 'urgent' 'use' 'usf' 'v'
 'valid' 'valu' 'vettam' 'want' 'wap' 'watch' 'way' 'week' 'wet' 'win'
 'winner' 'wkli' 'wonder' 'wont' 'word' 'wwwdbuknet' 'xxxmobilemovieclub'
 'xxxmobilemovieclubcomnqjkgighjjgcbl' 'ye' 'ü']

#### When you have a matrix or data with most output of Zeros it is reffered to as sparse matrrices. It will be inefficient to store all the 0 values, instead we store the location and values of non-zero elements

In [8]:
# to view array we have to expand the matrix into a dataframe
X_count_df = pd.DataFrame(X_counts_sample.toarray())

X_count_df

,0,1,2,3,4,5,6,7,8,9,...,191,192,193,194,195,196,197,198,199,200
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
X_count_df.columns = count_vect_sample.get_feature_names_out()
X_count_df

,08002986030,08452810075over18,09061701461,1,100,100000,11,12,150pday,16,...,winner,wkli,wonder,wont,word,wwwdbuknet,xxxmobilemovieclub,xxxmobilemovieclubcomnqjkgighjjgcbl,ye,ü
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## N-GRAMs

#### Definition
create document term matrix still with the count, but this time instead of returning single words in columns, they represent combinations of adjacent words defined by length n in the body-text

In [10]:
df.head()

,label,body_text
0,ham,I've been searching for the right words to thank you for this breather. I promise i wont take yo...
1,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...
2,ham,"Nah I don't think he goes to usf, he lives around here though"
3,ham,Even my brother is not like to speak with me. They treat me like aids patent.
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!

In [11]:

# create funtion to remove punctuation, change to lowercase, tokens words by spliting them with re, remove stop words and preform steming or lematisation
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in punct])
    tokens = re.split('\W+', text)
    text = " ".join([ps.stem(word) for word in tokens if word not in stop_words])
    return text


df['cleaned_text']= df['body_text'].apply(lambda x: clean_text(x))
df.head()

,label,body_text,cleaned_text
0,ham,I've been searching for the right words to thank you for this breather. I promise i wont take yo...,ive search right word thank breather promis wont take help grant fulfil promis wonder bless time
1,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...,free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri questionstd...
2,ham,"Nah I don't think he goes to usf, he lives around here though",nah dont think goe usf live around though
3,ham,Even my brother is not like to speak with me. They treat me like aids patent.,even brother like speak treat like aid patent
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,date sunday

In [12]:
# instantiate the vectoriser into an object
ngram_vect = CountVectorizer(ngram_range=(2,2))

# fit and transform the text to document term matrix
X_counts_ng = ngram_vect.fit_transform(df['cleaned_text'])

print(X_counts_ng.shape)
print(ngram_vect.get_feature_names_out())

(5568, 31275)
['008704050406 sp' '0089mi last' '0121 2025050' ... 'üll submit'
 'üll take' '〨ud even']

In [13]:
df_ng_sample = df[0:20]
df_ng_sample.head()

,label,body_text,cleaned_text
0,ham,I've been searching for the right words to thank you for this breather. I promise i wont take yo...,ive search right word thank breather promis wont take help grant fulfil promis wonder bless time
1,spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive ...,free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri questionstd...
2,ham,"Nah I don't think he goes to usf, he lives around here though",nah dont think goe usf live around though
3,ham,Even my brother is not like to speak with me. They treat me like aids patent.,even brother like speak treat like aid patent
4,ham,I HAVE A DATE ON SUNDAY WITH WILL!!,date sunday

In [14]:
# Using a smaller sample size of data for visibility
# Instantiate the vectoriser again into an object
ngram_vect_sample = CountVectorizer(ngram_range=(2,2))
X_counts_ng_sample = ngram_vect_sample.fit_transform(df_ng_sample['cleaned_text'])      # this is an array

print(X_counts_ng_sample.shape)
print(ngram_vect_sample.get_feature_names_out())

(20, 209)
['09061701461 claim' '100 20000' '100000 prize' '11 month' '12 hour'
 '150pday 6day' '16 tsandc' '20000 pound' '2005 text' '21st may'
 '4txtú120 poboxox36504w45wq' '6day 16' '81010 tc' '87077 eg'
 '87077 trywal' '87121 receiv' '87575 cost' '900 prize' 'aft finish'
 'aid patent' 'anymor tonight' 'appli 08452810075over18' 'appli repli'
 'ard smth' 'around though' 'bless time' 'breather promis' 'brother like'
 'call 09061701461' 'call mobil' 'caller press' 'callertun caller'
 'camera free' 'cash 100' 'chanc win' 'claim 81010' 'claim call'
 'claim code' 'click httpwap' 'click wap' 'co free' 'code kl341'
 'colour mobil' 'comp win' 'copi friend' 'cost 150pday' 'credit click'
 'cri enough' 'csh11 send' 'cup final' 'custom select' 'da stock'
 'date sunday' 'dont miss' 'dont think' 'dont want' 'eg england'
 'eh rememb' 'england 87077' 'england macedonia' 'enough today'
 'entitl updat' 'entri questionstd' 'entri wkli' 'even brother' 'fa 87121'
 'fa cup' 'feel way' 'final tkt' 'fine way' 'finish lunch' 'finish ur'
 'first lar' 'free 08002986030' 'free call' 'free entri' 'free membership'
 'friend callertun' 'fulfil promis' 'go str' 'go tri' 'goalsteam news'
 'goe usf' 'gonna home' 'grant fulfil' 'ha ha' 'ha joke' 'help grant'
 'hl info' 'home soon' 'httpwap xxxmobilemovieclubcomnqjkgighjjgcbl'
 'im gonna' 'ive cri' 'ive search' 'jackpot txt' 'kim watch' 'kl341 valid'
 'lar da' 'latest colour' 'lccltd pobox' 'like aid' 'like speak'
 'link next' 'live around' 'lor ard' 'lor finish' 'lunch alreadi'
 'lunch go' 'macedonia dont' 'make wet' 'may 2005' 'mell mell' 'mell oru'
 'membership 100000' 'messag click' 'minnaminungint nurungu'
 'miss goalsteam' 'mobil 11' 'mobil camera' 'mobil updat' 'month entitl'
 'month ha' 'nah dont' 'name ye' 'nation team' 'naughti make'
 'network custom' 'news txt' 'next txt' 'nurungu vettam' 'oh kim'
 'oru minnaminungint' 'pay first' 'per request' 'pobox 4403ldnw1a7rw18'
 'poboxox36504w45wq 16' 'pound txt' 'press copi' 'prize jackpot'
 'prize reward' 'promis wonder' 'promis wont' 'questionstd txt'
 'ratetc appli' 'receiv entri' 'receivea 900' 'rememb spell' 'repli hl'
 'request mell' 'reward claim' 'right word' 'scotland 4txtú120'
 'search right' 'select receivea' 'send 87575' 'serious spell'
 'set callertun' 'six chanc' 'smth lor' 'soon dont' 'speak treat'
 'spell name' 'stock comin' 'str lor' 'stuff anymor' 'take help'
 'talk stuff' 'tc wwwdbuknet' 'team 87077' 'text fa' 'thank breather'
 'think goe' 'tkt 21st' 'tonight ive' 'treat like' 'tri month'
 'trywal scotland' 'tsandc appli' 'txt csh11' 'txt messag' 'txt ratetc'
 'txt ur' 'txt word' 'updat co' 'updat latest' 'ur lunch' 'ur nation'
 'urgent week' 'use credit' 'usf live' 'valid 12' 'valu network'
 'vettam set' 'want talk' 'wap link' 'way feel' 'way gota' 'week free'
 'win cash' 'win fa' 'winner valu' 'wkli comp' 'wonder bless' 'wont take'
 'word claim' 'word thank' 'wwwdbuknet lccltd' 'xxxmobilemovieclub use'
 'ye naughti']

In [17]:
# Convert the array created byt the vectoriser to a data frame with pandas
X_counts_df_sample = pd.DataFrame(X_counts_ng_sample.toarray())

# Get the features from the dataframe
X_counts_df_sample.columns = ngram_vect_sample.get_feature_names_out()

X_counts_df_sample.head()

,09061701461 claim,100 20000,100000 prize,11 month,12 hour,150pday 6day,16 tsandc,20000 pound,2005 text,21st may,...,win fa,winner valu,wkli comp,wonder bless,wont take,word claim,word thank,wwwdbuknet lccltd,xxxmobilemovieclub use,ye naughti
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,1,0,0,0
1,0,0,0,0,0,0,0,0,1,1,...,1,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0